# Dockerfile.base (TEMPLATE/MOLDE)

FROM node:20-slim as monorepo_deps

WORKDIR /app

# 1. Copia arquivos de configuração da raiz do monorepo
COPY package.json package-lock.json turbo.json ./ 

# 2. Copia todos os package.json de todos os apps e packages
COPY apps/*/package.json apps/
COPY packages/*/package.json packages/

# 3. Instala todas as dependências (Camada que será cacheada!)
RUN npm install