# railway.toml
[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx turbo run build"

[[services]]
name = "web"
sourcePath = "apps/web"
startCommand = "npm start"
[services.env]
PORT = "3000"

[[services]]
name = "api-gateway" 
sourcePath = "apps/api-gateway"
startCommand = "node dist/main"
[services.env]
PORT = "3000"

[[services]]
name = "auth-service"
sourcePath = "apps/auth-service"
startCommand = "node dist/main" 
[services.env]
PORT = "3000"

[[services]]
name = "tasks-service"
sourcePath = "apps/tasks-service"
startCommand = "node dist/main"
[services.env]
PORT = "3000"

[[services]]
name = "notifications-service"
sourcePath = "apps/notifications-service"
startCommand = "node dist/main"
[services.env]
PORT = "3000"